name: FocusFlow Backend CI

on:
  push:
    branches: [ "**" ] 
  pull_request:
    branches: [ "**" ] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: focusflow       
          POSTGRES_USER: postgres      
          POSTGRES_PASSWORD: password   
        ports:
          - 5432:5432 
   
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' 

      - name: Build and run tests with Maven
        working-directory: ./focusflowbackend
        env:
          DB_URL: jdbc:postgresql://localhost:5432/focusflow
          DB_USERNAME: postgres
          DB_PASSWORD: password
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/focusflow
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
        run: mvn test 

